const express = require('express');
const app = express();
const cors = require('cors');
const helmet = require('helmet');
const dotenv = require('dotenv');
const authRoutes = require('./routes/auth.routes');
const userRoutes = require('./routes/user.routes');
const bookingRoutes = require('./routes/booking.routes');
const caregiverRoutes = require('./routes/caregiver.routes');
const path = require('path');
const adminRoutes = require('./routes/admin.routes');
const publicRoutes = require('./routes/public.routes');
const ratingRoutes = require('./routes/rating.routes');
const supportRoutes = require('./routes/support.routes');
const adminStatsRoutes = require('./routes/adminStats.routes');

dotenv.config();
app.use(cors());
app.use(helmet());
app.use(express.json());
app.use('/api/public', publicRoutes);
app.use('/api/auth', authRoutes);
app.use('/api/users', userRoutes);
app.use('/api/bookings', bookingRoutes);
app.use('/api/caregivers', caregiverRoutes);
app.use('/uploads', express.static(path.join(__dirname, 'uploads')));
app.use('/api/admin', adminRoutes);
app.use('/api/ratings', ratingRoutes);
app.use('/api/support', supportRoutes);
app.use('/api/admin', adminStatsRoutes);

module.exports = app;
